openapi: 3.0.3
info:
  title: PaintMixr OAuth Authentication API
  description: API endpoints for OAuth authentication flow with Supabase Auth
  version: 1.0.0
  contact:
    name: PaintMixr Team

servers:
  - url: https://paintmixr.vercel.app
    description: Production
  - url: http://localhost:3000
    description: Local development

paths:
  /auth/signin:
    get:
      summary: Sign-in page
      description: Displays OAuth provider buttons (Google, Microsoft, Facebook)
      tags:
        - Authentication
      responses:
        '200':
          description: Sign-in page rendered
          content:
            text/html:
              schema:
                type: string
        '302':
          description: Redirect if already authenticated
          headers:
            Location:
              schema:
                type: string
                example: /

  /api/auth/callback:
    get:
      summary: OAuth callback handler
      description: Handles redirect from Supabase Auth after OAuth provider authentication
      tags:
        - Authentication
      parameters:
        - name: code
          in: query
          required: false
          description: Authorization code from OAuth provider (handled by Supabase)
          schema:
            type: string
        - name: error
          in: query
          required: false
          description: Error code if authentication failed
          schema:
            type: string
        - name: error_description
          in: query
          required: false
          description: Human-readable error description
          schema:
            type: string
      responses:
        '302':
          description: Redirect to app with session cookie set
          headers:
            Location:
              schema:
                type: string
                example: /
            Set-Cookie:
              schema:
                type: string
                example: sb-access-token=...; HttpOnly; Secure; SameSite=Lax
        '401':
          description: Authentication failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                        example: OAUTH_FAILED
                      message:
                        type: string
                        example: OAuth authentication failed
        '500':
          description: Server error during callback processing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/auth/signout:
    post:
      summary: Sign out current user
      description: Clears session and signs out user from Supabase Auth
      tags:
        - Authentication
      security:
        - cookieAuth: []
      responses:
        '200':
          description: Successfully signed out
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Signed out successfully
        '302':
          description: Redirect to sign-in page
          headers:
            Location:
              schema:
                type: string
                example: /auth/signin
        '500':
          description: Error during sign-out
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /auth/error:
    get:
      summary: Authentication error page
      description: Displays authentication errors with user-friendly messages
      tags:
        - Authentication
      parameters:
        - name: error
          in: query
          required: true
          description: Error code
          schema:
            type: string
            enum:
              - access_denied
              - server_error
              - oauth_failed
              - invalid_request
      responses:
        '200':
          description: Error page rendered
          content:
            text/html:
              schema:
                type: string

components:
  schemas:
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: Machine-readable error code
          example: INTERNAL_ERROR
        message:
          type: string
          description: Human-readable error message
          example: An unexpected error occurred
        details:
          type: object
          description: Additional error context (development only)

  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: sb-access-token
      description: Supabase Auth session cookie (HTTP-only)

tags:
  - name: Authentication
    description: OAuth authentication endpoints

externalDocs:
  description: Supabase Auth Documentation
  url: https://supabase.com/docs/guides/auth
